#!/usr/bin/env python3
"""Rendering of the generated catalogs and the capability snapshot."""

from __future__ import annotations

import copy
import json
import re
from pathlib import Path
from typing import Any, Dict, List

from protocol_contract import CAPABILITIES_PATH, GENERATED_PATH, ROOT, ContractError, require_keys

def scala_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def option_projection(function: Dict[str, Any]) -> Dict[str, List[str]]:
    return {name: values for name, values in function["options"].items() if values}


def render_protocol_identity_scala(contract: Dict[str, Any]) -> str:
    protocol = contract["protocol"]
    major, minor, patch = protocol["version"].split(".")
    lines = [
        "// Generated by tools/generate.py. Do not edit.",
        "package io.github.zzjason.substrait.spark.v1",
        "",
        "object ProtocolIdentity {",
        f"  final val Version = {scala_string(protocol['version'])}",
        f"  final val Major = {major}",
        f"  final val Minor = {minor}",
        f"  final val Patch = {patch}",
        f"  final val SubstraitVersion = {scala_string(protocol['substraitVersion'])}",
        f"  final val CanonicalSha256 = {scala_string(protocol['canonicalSha256'])}",
        f"  final val FunctionExtensionUrn = {scala_string(protocol['functionExtensionUrn'])}",
        f"  final val PlanSemanticsTypeUrl = {scala_string(protocol['planSemanticsTypeUrl'])}",
        f"  final val SparkReadSemanticsTypeUrl = {scala_string(protocol['sparkReadSemanticsTypeUrl'])}",
        "}",
        "",
    ]
    return "\n".join(lines)


def scala_seq(values: List[str]) -> str:
    return "Vector(" + ", ".join(scala_string(value) for value in values) + ")"


def scala_map(options: Dict[str, List[str]]) -> str:
    if not options:
        return "Map.empty"
    entries = [f"{scala_string(name)} -> {scala_seq(values)}" for name, values in sorted(options.items())]
    return "Map(" + ", ".join(entries) + ")"


def render_function_catalog_scala(contract: Dict[str, Any]) -> str:
    lines = [
        "// Generated by tools/generate.py. Do not edit.",
        "package io.github.zzjason.substrait.spark.v1",
        "",
        "sealed trait FunctionKind",
        "object FunctionKind {",
        "  case object Scalar extends FunctionKind",
        "  case object Aggregate extends FunctionKind",
        "  case object Window extends FunctionKind",
        "}",
        "",
        "final case class FunctionDescriptor(",
        "    id: String, urn: String, signature: String, kind: FunctionKind,",
        "    callSites: Vector[String], options: Map[String, Vector[String]])",
        "",
        "object FunctionCatalog {",
        "  import FunctionKind._",
        "  val Functions: Vector[FunctionDescriptor] = Vector(",
    ]
    kind = {"SCALAR": "Scalar", "AGGREGATE": "Aggregate", "WINDOW": "Window"}
    for index, function in enumerate(contract["functions"]):
        suffix = "," if index + 1 < len(contract["functions"]) else ""
        options = option_projection(function)
        lines.append(
            "    FunctionDescriptor(" + ", ".join([
                scala_string(function["id"]), scala_string(function["urn"]),
                scala_string(function["signature"]), kind[function["kind"]],
                scala_seq(function["callSites"]), scala_map(options),
            ]) + ")" + suffix
        )
    lines += [
        "  )",
        "  val ByIdentity: Map[(FunctionKind, String, String), FunctionDescriptor] =",
        "    Functions.map(value => (value.kind, value.urn, value.signature) -> value).toMap",
        "}",
        "",
    ]
    return "\n".join(lines)


def render_protocol_identity_hpp(contract: Dict[str, Any]) -> str:
    protocol = contract["protocol"]
    major, minor, patch = protocol["version"].split(".")
    digest_bytes = ", ".join("0x" + protocol["canonicalSha256"][index:index + 2] for index in range(0, 64, 2))
    return "\n".join([
        "// Generated by tools/generate.py. Do not edit.",
        "#pragma once",
        "#include <array>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "namespace io::github::zzjason::substrait::spark::v1 {",
        f"inline constexpr std::string_view kProtocolVersion = {cpp_string(protocol['version'])};",
        f"inline constexpr std::uint32_t kProtocolMajor = {major};",
        f"inline constexpr std::uint32_t kProtocolMinor = {minor};",
        f"inline constexpr std::uint32_t kProtocolPatch = {patch};",
        f"inline constexpr std::string_view kSubstraitVersion = {cpp_string(protocol['substraitVersion'])};",
        f"inline constexpr std::string_view kCanonicalSha256Hex = {cpp_string(protocol['canonicalSha256'])};",
        f"inline constexpr std::array<std::uint8_t, 32> kCanonicalSha256 = {{{digest_bytes}}};",
        f"inline constexpr std::string_view kFunctionExtensionUrn = {cpp_string(protocol['functionExtensionUrn'])};",
        f"inline constexpr std::string_view kPlanSemanticsTypeUrl = {cpp_string(protocol['planSemanticsTypeUrl'])};",
        f"inline constexpr std::string_view kSparkReadSemanticsTypeUrl = {cpp_string(protocol['sparkReadSemanticsTypeUrl'])};",
        "}  // namespace io::github::zzjason::substrait::spark::v1",
        "",
    ])


def render_function_catalog_hpp(contract: Dict[str, Any]) -> str:
    count = len(contract["functions"])
    return "\n".join([
        "// Generated by tools/generate.py. Do not edit.",
        "#pragma once",
        "#include <array>",
        "#include <cstddef>",
        "#include <string_view>",
        "",
        "namespace io::github::zzjason::substrait::spark::v1 {",
        "enum class FunctionKind { kScalar, kAggregate, kWindow };",
        "struct FunctionOptionDescriptor {",
        "  std::string_view name;",
        "  std::string_view values_csv;",
        "};",
        "struct FunctionDescriptor {",
        "  std::string_view id;",
        "  std::string_view urn;",
        "  std::string_view signature;",
        "  FunctionKind kind;",
        "  std::string_view call_sites_csv;",
        "  const FunctionOptionDescriptor *options;",
        "  std::size_t option_count;",
        "};",
        f"extern const std::array<FunctionDescriptor, {count}> kFunctionCatalog;",
        "const FunctionDescriptor *FindFunction(FunctionKind kind, std::string_view urn, std::string_view signature);",
        "//! The declared descriptor of `name`, or nullptr when the identity does not declare it.",
        "const FunctionOptionDescriptor *FindFunctionOption(const FunctionDescriptor &function, std::string_view name);",
        "//! True when `value` is one of the values the identity declares for `name`.",
        "bool FunctionOptionAccepts(const FunctionDescriptor &function, std::string_view name, std::string_view value);",
        "}  // namespace io::github::zzjason::substrait::spark::v1",
        "",
    ])


def compact_json(value: Any) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True, allow_nan=False)


def render_function_catalog_cpp(contract: Dict[str, Any]) -> str:
    kind = {"SCALAR": "kScalar", "AGGREGATE": "kAggregate", "WINDOW": "kWindow"}
    lines = [
        "// Generated by tools/generate.py. Do not edit.",
        '#include "substrait_spark/function_catalog.hpp"',
        "",
        "namespace io::github::zzjason::substrait::spark::v1 {",
        "namespace {",
    ]
    option_tables = []
    for index, function in enumerate(contract["functions"]):
        options = option_projection(function)
        if not options:
            option_tables.append("nullptr")
            continue
        entries = ", ".join(
            "{" + cpp_string(name) + ", " + cpp_string(",".join(values)) + "}"
            for name, values in sorted(options.items())
        )
        symbol = f"kFunctionOptions{index}"
        option_tables.append(symbol)
        lines.append(f"constexpr FunctionOptionDescriptor {symbol}[] = {{{entries}}};")
    lines.append("}  // namespace")
    lines.append("")
    lines.append(f"const std::array<FunctionDescriptor, {len(contract['functions'])}> kFunctionCatalog = {{{{")
    for index, function in enumerate(contract["functions"]):
        options = option_projection(function)
        lines.append(
            "    {" + ", ".join([
                cpp_string(function["id"]), cpp_string(function["urn"]), cpp_string(function["signature"]),
                "FunctionKind::" + kind[function["kind"]], cpp_string(",".join(function["callSites"])),
                option_tables[index], str(len(options)),
            ]) + "},"
        )
    lines += [
        "}};",
        "",
        "const FunctionDescriptor *FindFunction(FunctionKind kind, std::string_view urn, std::string_view signature) {",
        "  for (const auto &function : kFunctionCatalog) {",
        "    if (function.kind == kind && function.urn == urn && function.signature == signature) return &function;",
        "  }",
        "  return nullptr;",
        "}",
        "",
        "const FunctionOptionDescriptor *FindFunctionOption(const FunctionDescriptor &function, std::string_view name) {",
        "  for (std::size_t index = 0; index < function.option_count; index++) {",
        "    if (function.options[index].name == name) return &function.options[index];",
        "  }",
        "  return nullptr;",
        "}",
        "",
        "bool FunctionOptionAccepts(const FunctionDescriptor &function, std::string_view name, std::string_view value) {",
        "  auto option = FindFunctionOption(function, name);",
        "  if (!option) return false;",
        "  auto values = option->values_csv;",
        "  std::size_t start = 0;",
        "  while (start <= values.size()) {",
        "    auto end = values.find(',', start);",
        "    auto candidate = values.substr(start, end == std::string_view::npos ? std::string_view::npos : end - start);",
        "    if (candidate == value) return true;",
        "    if (end == std::string_view::npos) break;",
        "    start = end + 1;",
        "  }",
        "  return false;",
        "}",
        "}  // namespace io::github::zzjason::substrait::spark::v1",
        "",
    ]
    return "\n".join(lines)


def payload_projection(contract: Dict[str, Any]) -> Dict[str, Any]:
    projection: Dict[str, Any] = {}
    for name, payload in contract["payloads"].items():
        entry: Dict[str, Any] = {
            "typeUrl": contract["protocol"][payload["typeUrlField"]],
            "encoding": payload["encoding"],
            "fields": payload["fields"],
        }
        for key in ("version", "rebaseModes", "sparkTypeNames", "sparkTypePattern"):
            if key in payload:
                entry[key] = payload[key]
        projection[name] = entry
    return projection


def render_capabilities(contract: Dict[str, Any]) -> str:
    projection = {
        "schemaVersion": contract["schemaVersion"],
        "protocolVersion": contract["protocol"]["version"],
        "canonicalSha256": contract["protocol"]["canonicalSha256"],
        "substraitVersion": contract["protocol"]["substraitVersion"],
        "matching": "EXACT_KIND_URN_COMPOUND_SIGNATURE",
        "unsupportedBehavior": "REJECT_BEFORE_BINDING_OR_EXECUTION",
        "planSemanticsTypeUrl": contract["protocol"]["planSemanticsTypeUrl"],
        "sparkReadSemanticsTypeUrl": contract["protocol"]["sparkReadSemanticsTypeUrl"],
        "payloads": payload_projection(contract),
        "functions": [
            {
                "id": function["id"],
                "urn": function["urn"],
                "signature": function["signature"],
                "kind": function["kind"],
                "callSites": function["callSites"],
                "options": option_projection(function),
            }
            for function in contract["functions"]
        ],
    }
    return json.dumps(projection, indent=2, ensure_ascii=False, allow_nan=False) + "\n"


def camel_case(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_") if part)


def payload_name(key: str) -> str:
    return key[0].upper() + key[1:]


def singular(name: str) -> str:
    return name[:-1] if name.endswith("s") and not name.endswith("ss") else name


def render_payload_schema_scala(contract: Dict[str, Any]) -> str:
    lines = [
        "// Generated by tools/generate.py. Do not edit.",
        "package io.github.zzjason.substrait.spark.v1",
        "",
        "object PayloadSchema {",
    ]

    def render_fields(fields: List[Dict[str, Any]], indent: str) -> None:
        names = sorted(field["name"] for field in fields)
        literals = ", ".join(scala_string(name) for name in names)
        lines.append(f"{indent}val Fields: Set[String] = Set({literals})")
        for field in fields:
            if field["kind"] == "ENUM":
                object_name = camel_case(field["name"])
                values = ", ".join(scala_string(value) for value in field["values"])
                lines.append(f"{indent}val {object_name}: Set[String] = Set({values})")
            elif field["kind"] == "STRUCT":
                lines.append(f"{indent}object {camel_case(field['name'])} {{")
                render_fields(field["fields"], indent + "  ")
                lines.append(f"{indent}}}")
            elif field["kind"] == "LIST":
                lines.append(f"{indent}object {camel_case(singular(field['name']))} {{")
                render_fields(field["element"]["fields"], indent + "  ")
                lines.append(f"{indent}}}")

    for name, payload in contract["payloads"].items():
        lines.append(f"  object {payload_name(name)} {{")
        if "version" in payload:
            lines.append(f"    val ProtocolVersion: Int = {payload['version']}")
        for key, scala_name in (("rebaseModes", "RebaseModes"),
                                ("sparkTypeNames", "PartitionTypeNames")):
            if key in payload:
                values = ", ".join(scala_string(value) for value in payload[key])
                lines.append(f"    val {scala_name}: Set[String] = Set({values})")
        if "sparkTypePattern" in payload:
            lines.append(f"    val PartitionTypePattern = {scala_string(payload['sparkTypePattern'])}")
        render_fields(payload["fields"], "    ")
        lines.append("  }")
    lines += ["}", ""]
    return "\n".join(lines)


def render_payload_schema_hpp(contract: Dict[str, Any]) -> str:
    lines = [
        "// Generated by tools/generate.py. Do not edit.",
        "#pragma once",
        "#include <array>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "namespace io::github::zzjason::substrait::spark::v1 {",
    ]
    emit_arrays: List[tuple] = []

    def prefixed(prefix: str, name: str) -> str:
        return prefix + camel_case(name)

    def collect(fields: List[Dict[str, Any]], prefix: str) -> None:
        names = sorted(field["name"] for field in fields)
        emit_arrays.append((prefix + "Fields", names))
        for field in fields:
            if field["kind"] == "ENUM":
                emit_arrays.append((prefixed(prefix, field["name"]), field["values"]))
            elif field["kind"] == "STRUCT":
                collect(field["fields"], prefixed(prefix, field["name"]))
            elif field["kind"] == "LIST":
                collect(field["element"]["fields"], prefixed(prefix, singular(field["name"])))

    for name, payload in contract["payloads"].items():
        collect(payload["fields"], "k" + payload_name(name))
        if "version" in payload:
            lines.append(f"inline constexpr std::uint32_t k{payload_name(name)}Version = {payload['version']};")
        for key, cpp_name in (("rebaseModes", "RebaseModes"),
                              ("sparkTypeNames", "PartitionTypeNames")):
            if key in payload:
                emit_arrays.append(("k" + payload_name(name) + cpp_name, payload[key]))
        if "sparkTypePattern" in payload:
            lines.append(f"inline constexpr std::string_view k{payload_name(name)}PartitionTypePattern = "
                         f"{cpp_string(payload['sparkTypePattern'])};")
    for symbol, values in emit_arrays:
        rendered = ", ".join(cpp_string(value) for value in values)
        lines.append(f"inline constexpr std::array<std::string_view, {len(values)}> {symbol} = {{{rendered}}};")
    lines += ["}  // namespace io::github::zzjason::substrait::spark::v1", ""]
    return "\n".join(lines)


def rendered_files(contract: Dict[str, Any]) -> Dict[str, bytes]:
    text_files = {
        "generated/scala/io/github/zzjason/substrait/spark/v1/ProtocolIdentity.scala": render_protocol_identity_scala(contract),
        "generated/scala/io/github/zzjason/substrait/spark/v1/FunctionCatalog.scala": render_function_catalog_scala(contract),
        "generated/cpp/include/substrait_spark/protocol_identity.hpp": render_protocol_identity_hpp(contract),
        "generated/cpp/include/substrait_spark/function_catalog.hpp": render_function_catalog_hpp(contract),
        "generated/cpp/src/function_catalog.cpp": render_function_catalog_cpp(contract),
        "generated/cpp/include/substrait_spark/payload_schema.hpp": render_payload_schema_hpp(contract),
        "generated/scala/io/github/zzjason/substrait/spark/v1/PayloadSchema.scala": render_payload_schema_scala(contract),
        "capabilities/capabilities.json": render_capabilities(contract),
    }
    return {path: text.encode("utf-8") for path, text in text_files.items()}


def write_rendered(files: Dict[str, bytes], root: Path) -> None:
    for relative, content in files.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)


def generated_relative_paths() -> List[str]:
    paths = []
    if GENERATED_PATH.exists():
        paths += [path.relative_to(ROOT).as_posix() for path in GENERATED_PATH.rglob("*") if path.is_file()]
    if CAPABILITIES_PATH.exists():
        paths.append(CAPABILITIES_PATH.relative_to(ROOT).as_posix())
    return sorted(paths)


def check_rendered(expected: Dict[str, bytes]) -> None:
    actual_paths = generated_relative_paths()
    expected_paths = sorted(expected)
    errors = []
    for path in sorted(set(actual_paths) | set(expected_paths)):
        target = ROOT / path
        if path not in expected:
            errors.append(f"extra: {path}")
        elif not target.exists():
            errors.append(f"missing: {path}")
        elif target.read_bytes() != expected[path]:
            errors.append(f"changed: {path}")
    if errors:
        raise ContractError("generated output is stale:\n" + "\n".join(errors))


